// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DomainEntity.Models;
using Microsoft.EntityFrameworkCore;

namespace DomainEntity.Models;

public partial class pishroContext : DbContext
{
    public pishroContext(DbContextOptions<pishroContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<InvoiceCustomer> InvoiceCustomer { get; set; }

    public virtual DbSet<InvoiceRegister> InvoiceRegister { get; set; }

    public virtual DbSet<Invoices> Invoices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InvoiceCustomer>(entity =>
        {
            entity.HasOne(d => d.Customer).WithMany(p => p.InvoiceCustomer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceCustomer_Customer");

            entity.HasOne(d => d.Invoice).WithMany(p => p.InvoiceCustomer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceCustomer_Invoices");
        });

        modelBuilder.Entity<InvoiceRegister>(entity =>
        {
            entity.HasOne(d => d.Invoice).WithMany(p => p.InvoiceRegister)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InvoiceRegister_Invoices");
        });

        modelBuilder.Entity<Invoices>(entity =>
        {
            entity.HasKey(e => e.InvoiceId).HasName("PK_Invoice");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}