// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DomainEntity.Models;

public partial class Customer
{
    [Key]
    public int CustomerId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Family { get; set; }

    [Required]
    [StringLength(50)]
    public string Mobile { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    public int CodeMelli { get; set; }
    public bool IsDeleted { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<InvoiceCustomer> InvoiceCustomer { get; } = new List<InvoiceCustomer>();
}