// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DomainEntity.Models;

public partial class InvoiceCustomer
{
    [Key]
    public int InvoiceCustomerId { get; set; }

    public int CustomerId { get; set; }

    public bool IsDeleted { get; set; }
    public int InvoiceId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("InvoiceCustomer")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("InvoiceId")]
    [InverseProperty("InvoiceCustomer")]
    public virtual Invoices Invoice { get; set; }
}